apiVersion: v1
kind: Pod
metadata:
  name: go-demo-app
  labels:
    type: stack
spec:
  containers:
  - image: mongo:3.3
    name: db
  - name: api
    image: sachinnicky/go-demo-app:latest
    env:
    - name: DB
      value: localhost
