apiVersion: v1
kind: Pod
metadata:
  name: db
  labels:
    type: db
    vendor: MongoLabs
spec:
  containers:
  - image: mongo:3.3
    name: db
    command: ["mongod"]
    args: ["--rest", "--httpinterface"]

